In [1]:
import numpy as np

x = np.array([1,2,3,4,5])

In [2]:
print (x)
print (type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
x.dtype

dtype('int32')

In [4]:
x.shape

(5,)

In [5]:
y = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
print (y)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [6]:
y.shape

(4, 4)

In [7]:
y.size

16

In [8]:
x = np.array(["hello", "world"])
print (x)

['hello' 'world']


In [9]:
print('Shape: ', x.shape)
print('type: ',type(x))
print('dtype: ', x.dtype)

Shape:  (2,)
type:  <class 'numpy.ndarray'>
dtype:  <U5


In [10]:
x = np.array([1, 2, 'Hello'])
print (x)
print('Shape: ', x.shape)
print('type: ',type(x))
print('dtype: ', x.dtype)

['1' '2' 'Hello']
Shape:  (3,)
type:  <class 'numpy.ndarray'>
dtype:  <U11


In [11]:
x = np.array([1, 2, 2.5, 4.5])
print(x, x.dtype)

[ 1.   2.   2.5  4.5] float64


In [12]:
x = np.array([1, 2.5, 3, 4.5], dtype=np.int64)
print(x)
print('dtype: ',x.dtype)

[1 2 3 4]
dtype:  int64


In [13]:
x = np.array([1, 2, 3, 4, 5])
np.save('my_array',x)

In [14]:
y = np.load('my_array.npy')
print (y)

[1 2 3 4 5]
