In [2]:
import numpy as np

In [3]:
x = np.arange(25).reshape(5,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [4]:
print(x|x>10)

[[False False False False False]
 [False False False False False]
 [False  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [5]:
print(x[x>10])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [6]:
print(x[x<=7])

[0 1 2 3 4 5 6 7]


In [7]:
print(x[(x>10) & (x<17)])

[11 12 13 14 15 16]


In [9]:
x[(x>10) & (x<17)] = -1
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]


In [11]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 2, 4, 10])

print(np.intersect1d(x, y))
print(np.union1d(x, y))
print(np.setdiff1d(x, y))

[2 4]
[ 1  2  3  4  5  6  7 10]
[1 3 5]


In [12]:
x = np.random.randint(1, 11, size=(10,))
print(x)

[ 7  7  4  2  5  6  8  4 10  6]


In [13]:
print(np.sort(x))
print(x)

[ 2  4  4  5  6  6  7  7  8 10]
[ 7  7  4  2  5  6  8  4 10  6]


In [15]:
print(np.sort(np.unique(x)))

[ 2  4  5  6  7  8 10]


In [16]:
print(x)

[ 7  7  4  2  5  6  8  4 10  6]


In [17]:
x.sort()
print(x)

[ 2  4  4  5  6  6  7  7  8 10]


In [18]:
x = np.random.randint(1, 11, size=(5,5))
print(x)

[[ 9  9  8  8  7]
 [10  8  3  3  8]
 [10  8  5  8  7]
 [ 4  7  4  6  8]
 [ 4  3  8  2 10]]


In [19]:
print(np.sort(x,axis=0))

[[ 4  3  3  2  7]
 [ 4  7  4  3  7]
 [ 9  8  5  6  8]
 [10  8  8  8  8]
 [10  9  8  8 10]]


In [20]:
print(np.sort(x,axis=1))

[[ 7  8  8  9  9]
 [ 3  3  8  8 10]
 [ 5  7  8  8 10]
 [ 4  4  6  7  8]
 [ 2  3  4  8 10]]


In [21]:
X = np.arange(1,25).reshape(5,5)
print(x)

ValueError: cannot reshape array of size 24 into shape (5,5)

In [22]:
X = np.arange(1,26).reshape(5,5)

In [23]:
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [24]:
print(x[x%2==0])

[ 8  8 10  8  8 10  8  8  4  4  6  8  4  8  2 10]
