In [1]:
import numpy as np
 
my_list = [1, 2, 3, 4, 5]
np.array(my_list)

array([1, 2, 3, 4, 5])

In [2]:
x = np.zeros((3,4))
print (x)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [3]:
print ('dType: ', x.dtype)

dType:  float64


In [4]:
x = np.zeros((3,4),dtype=int)
print (x)
print ('dType: ', x.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
dType:  int32


In [5]:
x = np.ones((4,3))
print (x)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [6]:
x = np.full((4,5),5)
print (x)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [7]:
print('dType: ', x.dtype)

dType:  int32


In [8]:
x = np.eye(5)
print (x)

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [9]:
x = np.diag([10,20,30,40])
print (x)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


`arange` function accepts 3 arguments
`np.arange(start, stop, step)`

In [13]:
x = np.arange(10)
print (x)

[0 1 2 3 4 5 6 7 8 9]


Start is inclusive, Stop is exclusive

In [14]:
x = np.arange(4, 10)
print(x)

[4 5 6 7 8 9]


In [15]:
x = np.arange(4, 14, 3)
print (x)

[ 4  7 10 13]


### `linspace` - start and stop inclusive

In [16]:
x = np.linspace(0, 25, 10)
print (x)

[  0.           2.77777778   5.55555556   8.33333333  11.11111111
  13.88888889  16.66666667  19.44444444  22.22222222  25.        ]


In [17]:
x = np.linspace(0, 25, 10, endpoint=False)
print (x)

[  0.    2.5   5.    7.5  10.   12.5  15.   17.5  20.   22.5]


### Creating Rank 2 arrays (2D array)

In [18]:
x = np.arange(20)
print (x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [19]:
x = np.reshape(x, (4,5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [20]:
x = np.reshape(x, (10,2))
print (x)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [21]:
y = np.arange(20).reshape((10,2))
print (y)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [22]:
x = np.linspace(0, 50, 10, endpoint=False).reshape((5,2))
print (x)

[[  0.   5.]
 [ 10.  15.]
 [ 20.  25.]
 [ 30.  35.]
 [ 40.  45.]]


### Creating random values

In [23]:
x = np.random.random((3,3))
print (x)

[[ 0.99524966  0.20341905  0.28863288]
 [ 0.55785824  0.34202705  0.88157969]
 [ 0.24012058  0.79306612  0.39821037]]


`randint` takes 3 arguments
`np.random.randint(LowerBound, UpperBound, (shape))`
LowerBound - Inclusive
UpperBound - Exclusive

In [24]:
x = np.random.randint(4, 15, (3, 2))
print (x)

[[ 6  4]
 [10 11]
 [ 8  8]]


Create random number array with given mean and statndard deviation

mean = 0
standard deviation = 0.1

In [25]:
x = np.random.normal(0, 0.1, size=(1000, 1000))
print (x)

[[-0.10564314 -0.09144132  0.12767337 ..., -0.05551705  0.21651586
   0.08088029]
 [-0.03743322 -0.1325416   0.13595293 ...,  0.03493501  0.09219395
   0.01672728]
 [-0.07878196  0.04609144  0.01181563 ...,  0.0336763   0.01450461
  -0.04203852]
 ..., 
 [ 0.01994166 -0.01859801  0.14895094 ...,  0.20258664 -0.00995924
  -0.08437954]
 [ 0.03259374  0.05583825  0.02798297 ...,  0.04024336 -0.00968506
  -0.09047441]
 [-0.05880993 -0.10434932  0.00921925 ...,  0.06047589 -0.00393775
   0.04808664]]


In [26]:
print('mean: ', x.mean())
print('std: ', x.std())
print('max: ', x.max())
print('min: ', x.min())
print('# Positive: ', (x > 0).sum())
print('# Negative: ', (x < 0).sum())

mean:  -3.47032509932e-05
std:  0.10009683457
max:  0.481767073103
min:  -0.490900494298
# Positive:  499872
# Negative:  500128
