In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4, 5])
print (x)

[1 2 3 4 5]


In [4]:
print('1st Element: ', x[0])
print('2nd Element: ', x[1])
print('5th Element: ', x[4])

1st Element:  1
2nd Element:  2
5th Element:  5


In [5]:
print('1st Element: ', x[-5])
print('2nd Element: ', x[-4])
print('5th Element: ', x[-1])

1st Element:  1
2nd Element:  2
5th Element:  5


In [6]:
x[3] = 20
print(x)

[ 1  2  3 20  5]


In [7]:
x = np.arange(1,10).reshape((3,3))
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
print('Element at (0,0): ', x[0, 0])
print('Element at (0,1): ', x[0, 1])
print('Element at (2,2): ', x[2, 2])

Element at (0,0):  1
Element at (0,1):  2
Element at (2,2):  9


In [9]:
x[0, 0] = 20
print(x)

[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [10]:
x = np.array([1, 2, 3, 4, 5])
print(x)

x = np.delete(x, [0,4])
print(x)

[1 2 3 4 5]
[2 3 4]


In [11]:
y = np.arange(1,10).reshape((3,3))
print(y)

w = np.delete(y, 0, axis=0)
print('\n',w)

v = np.delete(y, [0, 2], axis=1)
print('\n',v)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[4 5 6]
 [7 8 9]]

 [[2]
 [5]
 [8]]


In [12]:
x = np.array([1, 2, 3, 4, 5])
print(x)

x = np.append(x, 6)
print(x)

[1 2 3 4 5]
[1 2 3 4 5 6]


In [13]:
x = np.append(x, [7, 8, 9])
print(x)

[1 2 3 4 5 6 7 8 9]


In [14]:
y = np.arange(1,10).reshape((3,3))
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
w = np.append(y, [[10, 11, 12]],axis=0)
print(w)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [16]:
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
v = np.append(y, [[10], [11], [12]], axis=1)
print(v)

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [20]:
x = np.array([1, 2, 5, 6, 7])
print(x)

x = np.insert(x, 2, [3, 4])
print(x)

[1 2 5 6 7]
[1 2 3 4 5 6 7]


In [21]:
y = np.arange(1,10).reshape((3,3))
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
w = np.insert(y, 1, [10, 11, 12], axis=0)
print(w)

[[ 1  2  3]
 [10 11 12]
 [ 4  5  6]
 [ 7  8  9]]


In [24]:
v = np.insert(y, 1, [30, 40, 45], axis=1)
print(v)

[[ 1 30  2  3]
 [ 4 40  5  6]
 [ 7 45  8  9]]


In [25]:
x = np.array([1, 2])
print(x)

y = np.array([[3, 4], [5, 6]])
print(y)

[1 2]
[[3 4]
 [5 6]]


In [27]:
z = np.vstack((x,y))
print(z)

[[1 2]
 [3 4]
 [5 6]]


In [28]:
w = np.hstack((y, x.reshape(2, 1)))
print(w)

[[3 4 1]
 [5 6 2]]
